#define SKILL_CAT_WEAPON            0
#define SKILL_CAT_LANGUAGE          1
#define SKILL_CAT_PHYSICAL          2
#define SKILL_CAT_SPELL             3
#define SKILL_CAT_TRADE             4
#define MAX_SKILL_CAT               5

#define SKILL_NONE                 -1
#define SKILL_APPRAISE              0
#define SKILL_ASSASSINATE           1
#define SKILL_BACKSTAB              2
#define SKILL_BANDAGE               3
#define SKILL_BASH                  4
#define SKILL_BEAR_GRASP            5
#define SKILL_BERSERK               6
#define SKILL_BLIND_FIGHTING        7
#define SKILL_CAMOUFLAGE            8
#define SKILL_CHARGE                9
#define SKILL_CLIMB                10
#define SKILL_COUNTER_ATTACK       11
#define SKILL_COVER_TRACKS         12
#define SKILL_CRITICAL_HIT         13
#define SKILL_DEATH_STRIKE         14
#define SKILL_DEMON_SLASH          15
#define SKILL_DISARM               16
#define SKILL_DISGUISE             17
#define SKILL_DODGE                18
#define SKILL_DRAGON_STRIKE        19
#define SKILL_EAGLE_CLAW           20
#define SKILL_EYE_GOUGE            21
#define SKILL_FIFTH                22
#define SKILL_FOURTH               23
#define SKILL_FRENZY               24
#define SKILL_GARROTE              25
#define SKILL_GUARD                26
#define SKILL_HAGGLE               27
#define SKILL_HEIST                28
#define SKILL_HIDE                 29
#define SKILL_INSPECT              30
#define SKILL_KICK                 31
#define SKILL_LAY_HANDS            32
#define SKILL_LOCUST_KICK          33
#define SKILL_MEDITATE             34
#define SKILL_MELEE                35
#define SKILL_MOUNTED_FIGHTING     36
#define SKILL_OFFHAND_ATTACK       37 
#define SKILL_PARRY                38
#define SKILL_PEEK                 39
#define SKILL_PICK_LOCK            40
#define SKILL_POWER_STRIKE         41
#define SKILL_PROBE                42
#define SKILL_PUNCH                43
#define SKILL_REGENERATION         44
#define SKILL_RESCUE               45
#define SKILL_RIDING               46
#define SKILL_SCAN                 47
#define SKILL_SEARCHING            48
#define SKILL_SECOND               49
#define SKILL_SHADOW_DANCE         50
#define SKILL_SHIELD               51  
#define SKILL_SNEAK                52
#define SKILL_SPIN_KICK            53 
#define SKILL_STEAL                54
#define SKILL_STUN                 55
#define SKILL_SWEEP                56
#define SKILL_SWEEPING_KICK        57
#define SKILL_SWIMMING             58
#define SKILL_THIRD                59
#define SKILL_TIGER_PAW            60
#define SKILL_TRACK                61
#define SKILL_TRANCE               62
#define SKILL_TRANSFER_ENERGY      63
#define SKILL_TRIP                 64
#define SKILL_TUMBLE               65
#define SKILL_UNTRAP               66

#define LANG_PRIMAL                67
#define LANG_HUMANIC               68
#define LANG_ELVISH                69
#define LANG_GNOMISH               70
#define LANG_DWARVISH              71
#define LANG_THENNISH              72
#define LANG_ENTISH                73
#define LANG_CENTAUR               74
#define LANG_SLISP                 75
#define LANG_OGRISH                76
#define LANG_TROLLISH              77
#define LANG_ORCISH                78
#define LANG_GOBLISH               79
#define LANG_VYANIAN               80
#define MAX_LANGUAGE               81

#define SPELL_FIRST                81
#define SPELL_AMNESIA              81
#define SPELL_ANIMATE_CLAY         82
#define SPELL_ANIMATE_DEAD         83
#define SPELL_ARMOR                84
#define SPELL_BANISHMENT           85
#define SPELL_BARKSKIN             86
#define SPELL_BLESS                87
#define SPELL_BLIND                88
#define SPELL_BLINDING_LIGHT       89
#define SPELL_BLINK                90
#define SPELL_BURNING_HANDS        91
#define SPELL_CALL_LIGHTNING       92
#define SPELL_CALM                 93
#define SPELL_CAUSE_CRITICAL       94
#define SPELL_CAUSE_LIGHT          95
#define SPELL_CAUSE_SERIOUS        96
#define SPELL_CHAIN_LIGHTNING      97
#define SPELL_CHILLING_TOUCH       98
#define SPELL_CONFUSE              99
#define SPELL_CONTINUAL_LIGHT     100 
#define SPELL_CREATE_FEAST        101
#define SPELL_CREATE_FOOD         102
#define SPELL_CREATE_LIGHT        103
#define SPELL_CREATE_WATER        104
#define SPELL_CURE_BLINDNESS      105
#define SPELL_CURE_CRITICAL       106
#define SPELL_CURE_DISEASE        107
#define SPELL_CURE_LIGHT          108
#define SPELL_CURE_POISON         109
#define SPELL_CURE_SERIOUS        110
#define SPELL_CURSE               111
#define SPELL_DETECT_EVIL         112
#define SPELL_DETECT_GOOD         113
#define SPELL_DETECT_HIDDEN       114
#define SPELL_DETECT_INVISIBLE    115
#define SPELL_DETECT_MAGIC        116
#define SPELL_DISPLACE            117
#define SPELL_DRAIN_LIFE          118
#define SPELL_EAGLE_EYE           119
#define SPELL_FAERIE_FIRE         120
#define SPELL_FEAR                121
#define SPELL_FIND_FAMILIAR       122
#define SPELL_FIRE_SHIELD         123
#define SPELL_FIREBALL            124

#define SPELL_FREEZE              125
#define SPELL_GIFT_OF_TONGUES     126
#define SPELL_GREATER_ANIMATION   127
#define SPELL_HALLUCINATE         128
#define SPELL_HARM                129
#define SPELL_HAWKS_VIEW          130
#define SPELL_HEAL                131
#define SPELL_HOLY_WRATH          132
#define SPELL_ICE_STORM           133
#define SPELL_IDENTIFY            134
#define SPELL_IGNITE_WEAPON       135   
#define SPELL_INFRAVISION         136  
#define SPELL_INVISIBILITY        137
#define SPELL_LIGHTNING_BOLT      138
#define SPELL_LOCUST_SWARM        139
#define SPELL_MAGIC_MAPPING       140
#define SPELL_MAGIC_MISSILE       141
#define SPELL_MIND_BLADE          142
#define SPELL_MINOR_ENCHANTMENT   143
#define SPELL_MISTS_SLEEP         144
#define SPELL_MYSTIC_SHIELD       145
#define SPELL_NEUTRALIZE          146
#define SPELL_OGRE_STRENGTH       147
#define SPELL_POISON_CLOUD        148  
#define SPELL_POLYMORPH           149
#define SPELL_PROTECT_LIFE        150
#define SPELL_PROT_PLANTS         151
#define SPELL_RECALL              152
#define SPELL_REMOVE_CURSE        153
#define SPELL_REPLICATE           154
#define SPELL_REVITALIZE          155
#define SPELL_SANCTIFY            156
#define SPELL_SENSE_LIFE          157
#define SPELL_SHOCK               158
#define SPELL_SILENCE             159
#define SPELL_SLAY                160
#define SPELL_SLEEP               161 
#define SPELL_SLOW                162
#define SPELL_SUMMON              163
#define SPELL_TAME                164
#define SPELL_TRUE_SIGHT          165
#define SPELL_TURN_UNDEAD         166
#define SPELL_VITALITY            167
#define SPELL_WEB                 168
#define SPELL_ASTRAL_GATE         169
#define SPELL_FLOAT               170
#define SPELL_PASS_DOOR           171
#define SPELL_ACID_BLAST          172

#define SPELL_ACID_STORM          173
#define SPELL_FLY                 174
#define SPELL_HASTE               175
#define SPELL_PRISMIC_MISSILE     176
#define SPELL_MAELSTROM           177
#define SPELL_RESURRECT           178
#define SPELL_BALM                179
#define SPELL_SURCEASE            180
#define SPELL_LESSER_SUMMONING    181
#define SPELL_REQUEST_ALLY        182
#define SPELL_SENSE_DANGER        183
#define SPELL_RESTORATION         184
#define SPELL_FLAME_STRIKE        185
#define SPELL_RESIST_FIRE         186
#define SPELL_RESIST_COLD         187
#define SPELL_INVULNERABILITY     188
#define SPELL_TRANSFER            189
#define SPELL_PROTECT_EVIL        190
#define SPELL_PROTECT_GOOD        191
#define SPELL_WIZARD_LOCK         192
#define SPELL_YOUTH               193

#define SPELL_MAJOR_ENCHANTMENT   194
#define SPELL_AUGURY              195
#define SPELL_RESIST_ACID         196
#define SPELL_RESIST_SHOCK        197
#define SPELL_THORN_SHIELD        198
#define SPELL_ICE_LANCE           199
#define SPELL_ION_SHIELD          200
#define SPELL_METEOR_SWARM        201
#define SPELL_GROUP_CRITICAL      202
#define SPELL_GROUP_SERIOUS       203
#define SPELL_PURIFY              204
#define SPELL_WATER_BREATHING     205
#define SPELL_WITHER              206
#define SPELL_CONSTRUCT_GOLEM     207
#define SPELL_CONFLAGRATION       208
#define SPELL_CONJURE_ELEMENTAL   209
#define SPELL_POULTICE            210
#define SPELL_SCRY                211
#define SPELL_FIND_MOUNT          212
#define SPELL_OBSCURE             213

#define TRADE_FIRST               214
#define TRADE_COOKING             214
#define TRADE_LEATHERING          215
#define TRADE_METALURGY           216
#define TRADE_WOODWORKING         217
#define MAX_TRADE                 218

#define WEAPON_FIRST              218
#define WEAPON_UNARMED            218
#define WEAPON_DAGGER             219
#define WEAPON_SWORD              220
#define WEAPON_CLUB               221
#define WEAPON_STAFF              222
#define WEAPON_POLEARM            223
#define WEAPON_MACE               224
#define WEAPON_WHIP               225
#define WEAPON_AXE                226
#define WEAPON_BOW                227
#define WEAPON_SPEAR              228
#define MAX_SKILL                 229


extern trainer_data*  trainer_list;

extern const char* skill_cat_name [ MAX_SKILL_CAT ];


/*
 *   LANGUAGES
 */


extern int        max_language;
extern flag_data  lang_flags;


int get_language  ( char_data*, int );
