#TABLE

21

beat~
6
0
0
0
You @rbeat@n your chest like a @grampaging gorilla!~
$1 @rbeats@n $s chest @ysquealing@n with a @rmighty fury!~
You commence @rBeating@n $N about the head and shoulders.~
@yMadly squealing,@n $1 begins @rbeating@n $N about the head and shoulders.~
With an @yinsane squeal,@n $1 begins to @rBeat@n you about the head and shoulders.~
You have dream of a severe beating about the head and shoulders.~
~
~
~
~
~
~
~
~
~
~
~
~

bhand~
8
0
0
1
You bring a hand back... looking for someone to backhand.~
@n brings $s hand back menacingly... readying a mighty backhand.~
You bring a hand back.... and deliver a firm @rBackhand Slap@n to $N!~
$n brings $s hand back menacingly...  @rWhack!!@n delivering a mighty backhand to $N!~
$n brings $s hand back menacingly... @rWhack!!@n delivering a stinging backhand to your head!~
~
~
~
~
~
~
~
~
~
~
~
~
~

bscratch~
6
0
0
0
Scratching a painful itch, a fine cloud of dust erupts from your hairy back.~
$n squeals as $e tries to scratch $s back.  A fine cloud of dust erupts from $s hairy back.~
Out of the kindness of your heart, you scratch $N's back.~
$n kindly scratches $Ns back.  Jealous?~
$n scratches your back.   Aaahhhhh... doesnt that feel good?~
~
~
~
~
~
~
~
~
~
~
~
~
~

bully~
8
0
0
0
You look around for someone smaller than you.~
$n looks for someone to push around~
Picking $N up by the neck, you rattle $S brains until you get your way.~
$n grabs $N by the neck, rattling $S head until $e gets $s way.  What a bully!~
$n grabs you by the neck and begins to rattle your brains.  Better do what $e says!~
~
You begin speaking in tongues and hitting yourself.~
$n falls to the ground in a fit and bangs $s head on the ground.~
~
~
~
~
~
~
~
~
~
~

cry~
4
0
0
0
You cry softly, sniffling through your wet snout.~
$n cries softly, sniffling through $m wet snout.~
You cry on $s shoulder, sniffling through your wet snout.~
$n cries on $N's shoulder, sniffling and leaving a @gsnotty mess.@n~
$n cries on your shoulder, sniffling loudly in your ear.~
~
~
~
~
~
Looking $t you can't help but cry.~
$n looks $t and begins to cry.  Big orcish tears covering $s cheeks.~
~
~
~
~
~
~

ear~
6
0
0
0
~
~
Pushing a fat finger deeply into $N's ear, you search for lost treasure.~
$n buries a fat finger deeply into $N's ear.  Smiling at the wonderful wax $e finds.~
You feel a fat finger penetrate your ear.  $n smiles at the large amount of wax $e finds.~
Your dreams are disturbed by the presence of a fat finger probing your ear.~
With high hopes, you push a fat finger deep into your ear.  Who knows what may be hidden there?~
Pushing a fat finger deep into $s ear, $n roots around for lost treasure.~
~
~
~
~
~
~
~
~
~
~

grin~
6
0
0
0
Grinning evilly, you flash your tusks.~
Flashing $s tusks, $n grins evilly.~
Flashing your tusks, you grin evilly at $N.~
$n grins evilly at $N, flashing his tusks.~
Grinning evilly at you, $n's tusks become very apparent.~
~
~
~
~
~
~
~
~
~
~
~
~
~

grunt~
0
0
0
0
You grunt like a pig.~
$n grunts like a pig.~
You grunt like a pig at $N.~
$n grunts like a pig at $N.~
$n grunts like a pig at you.~
~
You grunt happily to yourself.~
$n grunts happily to $mself.~
~
~
~
~
~
~
~
~
~
~

heave~
8
0
0
0
~
~
@bSquealing@n with delight, you @yHeave@n $N high above your head in triumph.~
@bSquealing@n with delight, $n @yHeaves@n $N high above $s head in triumph.~
@bSquealing@n with delight, $n @yHeaves@n you high above $s head in triumph.~
~
~
~
@bSquealing@n with delight, you @yHeave@n $p high above your head in triumph.~
@bSquealing@n with delight, $n @yHeaves@ $p high above $s head in triumph.~
~
~
~
~
~
~
~
~

jump~
8
0
0
0
You jump up and down, both fat feet slapping the ground.~
$n's fat feet slap the ground as $e jumps up and down.~
You jump up and down on $N feeling $S insides @gsquish@n about.~
$n jumps up and down on $N, @gsquishing@n $S insides all about.~
$n jumps up and down on you, @gsquishing@n your insides all about.~
Someone jumps up and down on you, your insides will never be the same.~
~
~
~
~
~
~
~
~
~
~
~
~

knee~
8
0
1
1
You squat down low, knees popping loudly.~
$1 sits on $s haunches, knees popping loudly.~
You leap at $N, driving your knee deeply into $S thigh muscle.  Oh thats gotta hurt!~
$N @rScreams@n in pain as $1 drives a knee deeply into $S thigh.~
$1 leaps at you, @gDriving@n $s knee @rDeeply@n into your thigh.  That really hurt!!~
A @rpiercing pain@n erupts in your thigh.  Your dreams include orcish laughter.~
~
~
~
~
~
~
~
~
~
~
~
~

lick~
6
0
0
0
~
~
You lick $N with your @mcoarse, wet tongue@n, absentmindedly jabbing with your tusks.~
$n gives $N a @mlong, wet lick@n.~
Absentmindedly poking you with $s tusks, $n gives you a @mlong, wet lick@n.~
You feel a @mlong, wet lick@n, followed by the dull jab of tusks.~
You lick your tusks, @gdrooling@n in anticipation.~
$n licks $s tusks, @gdrooling@n in anticipation.~
~
~
~
~
~
~
~
~
~
~

nose~
5
0
0
0
You pick your nose, buried in deep thought.~
$n picks his nose, buried in deep thought.~
You pick your nose, wiping what you found on $N.~
$n picks his nose and wipes his finger on $N.~
$n picks his nose, and wipes the content of his slimy finger on your armor.~
~
You pick your nose and wipe it on your armor.~
$n picks his nose and wipes it all over his clothes.~
~
~
~
~
~
~
~
~
~
~

smile~
4
0
0
0
You smile happily, showing off your fine set of tusks.~
$n smiles happily, showing off $s fine set of tusks.~
Beaming a smile at $N, you flaunt your fine set of tusks.~
$n beams a smile at $N, $s fine orcish tusks gleaming.~
$n smiles happily at you, showing off $s fine set of tusks.~
~
~
~
~
~
~
~
~
~
~
~
~
~

snarl~
0
0
0
0
Your gnash your tusks and snarl.~
$n gnashes his tusks as $e snarls.~
You snarl at $N, flashing your tusks.~
$n snarls angrily at $N, flashing $s tusks.~
$n snarls angrily at you, flashing $s tusks.~
~
You snarl at yourself.~
$n snarls at $mself.~
~
~
~
~
~
~
~
~
~
~

snort~
0
0
0
0
Your snout curls as you snort loudly.~
$n's snout curls as $e snorts loudly.~
You snort angrily at $N.~
$n snorts angrily at $N.~
$n snorts angrily at you.~
~
You absentmindedly snort to yourself.~
$n absentmindedly snorts to $mself.~
~
~
~
~
~
~
~
~
~
~

squeal~
6
0
1
1
Waving your fists in the air, you emit an ear shattering @rBattle Squeal!@n~
Waving $s fists in the air, $n emits an ear shattering @rBattle Squeal!@n~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~

stomp~
8
0
1
1
@CStomping@n one foot down, then the other, you begin a famed orcish dance.~
@CStomping@n one foot down, then the other, $n begins a famed orcish dance~
You grab $N's hands and try to teach $M an orcish @cStomp@n.  It's not your fault $E has two left feet.~
Grabbing $N's hands, $n attempts to teach $M a famed orcish @cStomp@n.  $N winces as $n @cStomps@n upon $S feet.~
Grabbing your hands, $n attempts to teach you a famed orcish @cStomp@n.  Unfortunately, your feet get in the way. @rOUCH!@n~
~
~
~
Using both feet, you @CSTOMP@n repeatedly on $2!~
Using both feet, $n @CSTOMPS@n repeatedly on $2!~
~
~
~
~
~
~
~
~

think~
6
0
0
0
You slowly stroke your tusks, deep in thought.~
In deep thought, $n slowly strokes $s tusks.~
Slowly stroking your tusks, you think of $N's many problems.~
Slowly stroking $s tusks, $n thinks of $N's many problems.~
Slowly stroking his tusks, $n thinks of all your many problems.~
~
~
~
~
~
~
~
~
~
~
~
~
~

wrinkle~
6
0
0
0
Showing your disgust, you wrinkle your snout.~
Showing $s disgust, $n wrinkles his snout.~
With great disgust, you wrinkle your snout at $N.~
Showing great disgust, $n wrinkles $s snout at $N.~
Wrinkling $s snout, $n is disgusted with you.~
~
~
~
~
~
~
~
~
~
~
~
~
~

yawn~
0
0
0
0
You let out a big yawn.~
$n lets out a big yawn.~
You yawn at $N.~
$n yawns at $N.~
$n yawns at you.~
~
You let out a big yawn.~
$n lets out a big yawn.~
~
~
~
~
~
~
~
~
~
~


